feat: add security group for required tools
TRANSFR-Inc/terraform-aws-ecs_service pull request #1
Opened 2023-03-16 20:36 UTC by jhyelton

In order for our Datadog private location to connect to apps, we want to easily grant access from their security group similar to how we handle bastion access.  This also adds an "environment class" abstraction on top of environments, since we don't necessarily need to match the current backend environments.

2023-03-16 21:36 UTC, transfr-kennedy approved these changes
LGTM :shipit:

2023-03-17 20:55 UTC, transfr-kennedy requested changes
Very minor tweaks. Looks very good.

2023-03-17 20:55 UTC, transfr-kennedy commented on modules/healthcheck-monitoring/variables.tf
> +    description = "The URL to use for health checks. "
Is this internal, external, or both? If internal, amend to say something like "The inner-network URL..." or something similar.

2023-03-17 20:55 UTC, transfr-kennedy commented on modules/healthcheck-monitoring/variables.tf
> +    default = "/healthcheck"
Only one app uses `/healthcheck`; so I wouldn't make it the default. I wouldn't include a default in general until someone experienced like yourself defines a non-public "API" for operational concerns.

2023-03-17 20:55 UTC, transfr-kennedy commented on modules/healthcheck-monitoring/main.tf
> +resource "datadog_synthetics_test" "this" {
These are fine for V0 I suppose. Maybe we can make them more declarative in the future, but I appreciate not pre-optimizing.

2023-03-17 20:55 UTC, transfr-kennedy commented on modules/healthcheck-monitoring/main.tf
> +  message   = " @slack-platform-alerts-${var.env_name}"
Is this what maps alerts to "channel" or whatever? Should this be configurable?

2023-03-20 15:02 UTC, jhyelton commented on modules/healthcheck-monitoring/main.tf
> +  message   = " @slack-platform-alerts-${var.env_name}"
Yes, this maps to the channel.  It could be configurable, this was my attempt to have a 'working default' without requiring it in configuration.  I'll try to keep that but make it configurable as well.

2023-03-20 17:43 UTC, transfr-kennedy approved these changes
:shipit:

2023-03-20 20:51 UTC, merged